server:
    port: 8080
    shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "health,info,prometheus,metric"
  endpoint:
    health:
      show-details: always
      enabled: true
      show-components: always
