server:
    port: 8080
    shutdown: graceful

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5432/db"
    hikari:
      maximum-pool-size: 2
      max-lifetime: 115000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    defer-datasource-initialization: false
